# Numpy Task

### Instructions:
- Answer the following questions using NumPy only.
- Do not use Python loops unless explicitly stated.

## Part 1: Creating Arrays (3 Questions)


####  1) Create a NumPy array that contains all even numbers between 10 and 50 (inclusive).


In [4]:
import numpy as np

arr = np.arange(10,51,2)

print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]





#### 2) Create an array of shape (3, 4) filled with ones, then change all values in the last column to 0.



In [7]:
arr_2 = np.array([[1,2,3,4],
                [4,5,6,7],
                [7,8,9,10]])

print(arr_2)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]





#### 3) Create a NumPy array of 5 equally spaced numbers between -1 and 1.

In [8]:
arr_3 = np.linspace(-1,1,5)

print(arr_3)

[-1.  -0.5  0.   0.5  1. ]


## Part 2: Array Properties (3 Questions)

#### 1) Create array and then 
- Find its shape

- Number of elements

- Data type

In [13]:
arr_4 = np.random.rand(3,4)

print(arr_4)
print("Shape:", arr_4.shape)
print("Dimensions:", arr_4.size)
print("Data Type:", arr_4.dtype)


[[0.87622923 0.60570065 0.62993718 0.88037486]
 [0.52603112 0.24200666 0.00984658 0.62082534]
 [0.36343992 0.07235835 0.79372616 0.10696619]]
Shape: (3, 4)
Dimensions: 12
Data Type: float64


#### 2) Create a random array of size 10 and find:
- minimum value

- maximum value

- standard deviation

In [14]:
arr_5 = np.random.rand(10)

print(np.min(arr_5))
print(np.max(arr_5))
print(np.std(arr_5))

0.03424425924664831
0.9432698508984259
0.28371873026006855


#### 3) What is the difference between arr.size and arr.shape?

- Explain using an example.

arr.size: returns the total number of elements in the array (as a single integer).

arr.shape: returns the dimensions of the array (number of rows, columns, etc.) as a tuple.

In [15]:
arr_6 = np.array([1,2,3,3,4])

print('size:', arr_6.size)
print('shape:', arr_6.shape)

size: 5
shape: (5,)


## Part 3: Mathematical Operations & ufuncs (3 Questions)

#### 1) Create a new array that contains the square of each element without using loops.

In [16]:
# Given 

arr_7 = np.array([1, 2, 3, 4, 5])

squared_arr = arr_7 ** 2
print(squared_arr)

[ 1  4  9 16 25]


#### 2) Compute the mean and sum of all values in a 3×3 random matrix.

In [17]:
arr_8 = np.random.rand(3,3)

print(arr_8)
print('Mean:', np.mean(arr_8))
print('sum:', np.sum(arr_8))

[[0.48701648 0.48972446 0.52494585]
 [0.12656593 0.46790818 0.35849021]
 [0.16863491 0.43491016 0.8666773 ]]
Mean: 0.43609705460307935
sum: 3.924873491427714


#### 3) Compute the mean and sum of all values in a 3×3 random matrix.

In [18]:
arr_8 = np.random.rand(3,3)

print(arr_8)
print('Mean:', np.mean(arr_8))
print('sum:', np.sum(arr_8))

[[0.00958896 0.83219744 0.18296556]
 [0.76749099 0.04014289 0.58172942]
 [0.04542129 0.97903986 0.93088157]]
Mean: 0.4854953316422568
sum: 4.369457984780311


## Part 4: Indexing, Slicing & Boolean Indexing (4 Questions)

#### 1) Extract the middle four elements using slicing.

In [19]:
# Given 
arr = np.array([10, 20, 30, 40, 50, 60])

middle_four = arr[1:5]
print(middle_four)

[20 30 40 50]


#### 2) From the same array, extract all values greater than 25.

In [20]:
result = arr[arr>25]
print(result)

[30 40 50 60]


#### 3) Modify the array so that all values less than 30 become 0.

In [21]:
arr[arr < 30] = 0
print(arr)

[ 0  0 30 40 50 60]


#### 4) When would slicing be better than Boolean indexing?
Give one example.

when you want to select a continuous block of elements efficiently, without creating a new boolean array

In [22]:
arr = np.array([10, 20, 30, 40, 50, 60])

subset = arr[2:5]
print(subset)

[30 40 50]


## Part 5: Random Numbers & Performance (3 Questions)

#### 1) Generate a reproducible array of 15 random integers between 1 and 100.

In [27]:
np.random.seed(42)

arr = np.random.randint(1, 101, size=15)

print(arr)


[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]


#### 2) Create two arrays:

- one using a Python loop

- one using NumPy vectorization 

``to add 10 to each element.``

**Which one is faster and why?**

In [28]:
array = []
for i in range(10):
    array.append(i)

print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [30]:
arr = np.arange(0,10)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


#### 4) Why is `np.random.seed()` important in data science experiments?

makes the random numbers reproducible

## Part 6: Linear Algebra & Matrix Operations (2 Questions)

#### 1) Compute the determinant and inverse of a square matrix of your choice.

In [32]:
arr = np.array([[2, 1, 3],
                [1, 0, 2],
                [4, 1, 8]])

det = np.linalg.det(arr)
print("Determinant:", det)

inv = np.linalg.inv(arr)
print("Inverse:\n", inv)

Determinant: -1.0
Inverse:
 [[ 2.  5. -2.]
 [ 0. -4.  1.]
 [-1. -2.  1.]]


#### 2) What is the difference between:

- element-wise multiplication

- matrix multiplication
in NumPy?

* -> multiplies elements individually

@ or np.dot() -> performs proper matrix multiplication

## Bonus (Optional – Mindset Question)

#### How does NumPy help a Data Analyst think in a vectorized and mathematical way instead of a procedural one?

because it allows operations on entire arrays at once, instead of looping through elements individually.

Vectorized operations:
You can perform arithmetic, logical, and statistical operations

Avoid explicit loops:
No need for for loops to process data

Mathematical mindset:
Operations mimic linear algebra and matrix calculations